import { create } from 'zustand';
import { persist } from 'zustand/middleware';

// Comprehensive translations for different languages
const translations = {
  en: {
    nameCraft: 'NameCraft', // Keep in English for all languages
    discoverNames: 'Discover meaningful names from cultures around the world',
    chooseLanguage: 'Choose your language',
    getStarted: 'Get Started',
    swipeToContinue: 'Swipe up or tap to continue',
    chooseCategory: 'Choose Category',
    selectType: 'Select the type of names you\'re looking for',
    male: 'Male',
    female: 'Female',
    unisex: 'Unisex',
    traditionalMasculine: 'Traditional masculine names',
    beautifulFeminine: 'Beautiful feminine names',
    modernNeutral: 'Modern gender-neutral names',
    tapCard: 'Tap a card to continue your journey',
    chooseOrigin: 'Choose Origin',
    selectCultural: 'Select the cultural origin for your',
    names: 'names',
    chooseFeeling: 'Choose Feeling',
    selectEmotional: 'Select the emotional essence for your names',
    eachFeeling: 'Each feeling creates a unique emotional tone for your names',
    generateNames: 'Generate Names',
    fineTune: 'Fine-tune your preferences for perfect results',
    yourSelection: 'Your Selection',
    origin: 'Origin',
    gender: 'Gender',
    culturalOrigin: 'Cultural Origin',
    numberOfNames: 'Number of names',
    chooseBetween: 'Choose between 1 and 10 names to generate',
    generateBeautiful: 'Generate Beautiful Names',
    back: 'Back',
    next: 'Next',
    startOver: 'Start Over',
    feeling: 'Feeling',
    // Origins
    arabic: 'Arabic',
    islamic: 'Islamic',
    asian: 'Asian',
    western: 'Western',
    latin: 'Latin American',
    northAmerican: 'North American',
    european: 'European',
    african: 'African',
    jewish: 'Jewish',
    slavic: 'Slavic',
    scandinavian: 'Scandinavian',
    oceanic: 'Oceanic',
    korean: 'Korean',
    japanese: 'Japanese',
    global: 'Global Mix',
    // Feelings
    strong: 'Strong',
    soft: 'Soft',
    brave: 'Brave',
    mysterious: 'Mysterious',
    wise: 'Wise',
    joyful: 'Joyful',
    noble: 'Noble',
    peaceful: 'Peaceful',
    passionate: 'Passionate',
    unique: 'Unique',
    creative: 'Creative',
    adventurous: 'Adventurous',
    elegant: 'Elegant',
    loyal: 'Loyal',
    radiant: 'Radiant',
    readyToDiscover: 'Ready to Discover Names',
    generateBeautifulNames: 'Generate beautiful names',
    fromCulturalTraditions: 'from cultural traditions',
    meaningfulOrigins: 'Meaningful origins',
    meaningfulOriginsDesc: 'Names with deep cultural significance',
    culturalAuthenticity: 'Cultural authenticity',
    culturalAuthenticityDesc: 'Authentic names from real traditions',
    easyToCopy: 'Easy to copy & share',
    easyToCopyDesc: 'Simple copy and share functionality',
    // Additional keys for NameDisplay
    creatingNames: 'Creating Your Perfect Names',
    craftingNames: 'Crafting meaningful names with cultural depth...',
    weavingMagic: 'Weaving cultural magic into every name',
    yourBeautifulNames: 'Your Beautiful Names',
    tradition: 'tradition',
    copied: 'Copied!',
    copyAll: 'Copy All',
    generateMore: 'Generate More',
    // Region descriptions
    arabicDesc: 'Traditional Arabic names',
    islamicDesc: 'Islamic & Muslim names',
    asianDesc: 'Hindu, Sanskrit & Eastern names',
    westernDesc: 'Western & European names',
    jewishDesc: 'Jewish & Hebrew names',
    africanDesc: 'African & Tribal names',
    globalDesc: 'Global & International names',
    latinDesc: 'Latin & Mediterranean names',
    northAmericanDesc: 'North American names',
    europeanDesc: 'European Union names',
    slavicDesc: 'Slavic & Eastern European names',
    scandinavianDesc: 'Scandinavian & Nordic names',
    oceanicDesc: 'Oceanic & Pacific names',
    koreanDesc: 'Korean & East Asian names',
    japaneseDesc: 'Japanese & Zen names',
    // Region patterns
    arabicPattern: 'Traditional • Meaningful • Spiritual',
    islamicPattern: 'Religious • Blessed • Noble',
    asianPattern: 'Ancient Wisdom • Spiritual • Harmonious',
    westernPattern: 'Classic • Timeless • Strong',
    jewishPattern: 'Biblical • Sacred • Heritage',
    africanPattern: 'Powerful • Ancestral • Unique',
    globalPattern: 'Universal • Modern • Diverse',
    latinPattern: 'Romantic • Passionate • Elegant',
    northAmericanPattern: 'Modern • Independent • Bold',
    europeanPattern: 'Sophisticated • Cultural • Refined',
    slavicPattern: 'Strong • Traditional • Resilient',
    scandinavianPattern: 'Nature • Peaceful • Strong',
    oceanicPattern: 'Adventurous • Free • Natural',
    koreanPattern: 'Harmonious • Respectful • Balanced',
    japanesePattern: 'Minimalist • Peaceful • Meaningful',
    // Gender descriptions
    maleDesc: 'Strong, masculine names',
    femaleDesc: 'Elegant, feminine names',
    unisexDesc: 'Versatile, gender-neutral names',
    // Gender patterns
    malePattern: 'Bold • Powerful • Traditional',
    femalePattern: 'Graceful • Beautiful • Elegant',
    unisexPattern: 'Modern • Inclusive • Versatile',
    // Feeling descriptions
    uniqueDesc: 'One-of-a-kind names',
    strongDesc: 'Powerful & bold names',
    beautifulDesc: 'Elegant & graceful names',
    wiseDesc: 'Intelligent & thoughtful names',
    peacefulDesc: 'Calm & serene names',
    braveDesc: 'Courageous & fearless names',
    gentleDesc: 'Soft & tender names',
    mysteriousDesc: 'Enigmatic & intriguing names',
    joyfulDesc: 'Happy & cheerful names',
    nobleDesc: 'Dignified & honorable names',
    passionateDesc: 'Intense & emotional names',
    creativeDesc: 'Artistic & imaginative names',
    adventurousDesc: 'Bold & daring names',
    elegantDesc: 'Sophisticated & refined names',
    loyalDesc: 'Faithful & devoted names',
    radiantDesc: 'Bright & shining names',
    // Feeling patterns
    uniquePattern: 'Distinctive • Memorable • Special',
    strongPattern: 'Mighty • Courageous • Resilient',
    beautifulPattern: 'Graceful • Lovely • Charming',
    wisePattern: 'Intelligent • Insightful • Wise',
    peacefulPattern: 'Tranquil • Serene • Harmonious',
    bravePattern: 'Fearless • Bold • Heroic',
    gentlePattern: 'Tender • Kind • Gentle',
    mysteriousPattern: 'Mysterious • Enigmatic • Intriguing',
    joyfulPattern: 'Happy • Cheerful • Joyful',
    noblePattern: 'Dignified • Honorable • Noble',
    passionatePattern: 'Intense • Emotional • Fiery',
    creativePattern: 'Artistic • Imaginative • Creative',
    adventurousPattern: 'Bold • Daring • Adventurous',
    elegantPattern: 'Sophisticated • Refined • Elegant',
    loyalPattern: 'Faithful • Devoted • Loyal',
    radiantPattern: 'Bright • Shining • Radiant',
  },
  ar: {
    nameCraft: 'NameCraft', // Keep in English
    discoverNames: 'اكتشف أسماء ذات معنى من ثقافات حول العالم',
    chooseLanguage: 'اختر لغتك',
    getStarted: 'ابدأ',
    swipeToContinue: 'اسحب لأعلى أو اضغط للمتابعة',
    chooseCategory: 'اختر الفئة',
    selectType: 'اختر نوع الأسماء التي تبحث عنها',
    male: 'ذكر',
    female: 'أنثى',
    unisex: 'للجنسين',
    traditionalMasculine: 'أسماء ذكورية تقليدية',
    beautifulFeminine: 'أسماء أنثوية جميلة',
    modernNeutral: 'أسماء حديثة محايدة',
    tapCard: 'اضغط على البطاقة لمتابعة رحلتك',
    chooseOrigin: 'اختر الأصل',
    selectCultural: 'اختر الأصل الثقافي لأسمائك',
    names: 'أسماء',
    chooseFeeling: 'اختر المشاعر',
    selectEmotional: 'اختر الجوهر العاطفي لأسمائك',
    eachFeeling: 'كل شعور يخلق نبرة عاطفية فريدة لأسمائك',
    generateNames: 'إنشاء الأسماء',
    fineTune: 'اضبط تفضيلاتك للحصول على نتائج مثالية',
    yourSelection: 'اختيارك',
    origin: 'الأصل',
    gender: 'الجنس',
    culturalOrigin: 'الأصل الثقافي',
    numberOfNames: 'عدد الأسماء',
    chooseBetween: 'اختر بين 1 و 10 أسماء للإنشاء',
    generateBeautiful: 'إنشاء أسماء جميلة',
    back: 'رجوع',
    next: 'التالي',
    startOver: 'ابدأ من جديد',
    feeling: 'المشاعر',
    // Origins in Arabic
    arabic: 'عربي',
    islamic: 'إسلامي',
    asian: 'آسيوي',
    western: 'غربي',
    latin: 'أمريكا اللاتينية',
    northAmerican: 'أمريكا الشمالية',
    european: 'أوروبي',
    african: 'أفريقي',
    jewish: 'يهودي',
    slavic: 'سلافي',
    scandinavian: 'إسكندنافي',
    oceanic: 'المحيط الهادئ',
    korean: 'كوري',
    japanese: 'ياباني',
    global: 'مزيج عالمي',
    // Feelings in Arabic
    strong: 'قوي',
    soft: 'لطيف',
    brave: 'شجاع',
    mysterious: 'غامض',
    wise: 'حكيم',
    joyful: 'مبهج',
    noble: 'نبيل',
    peaceful: 'مسالم',
    passionate: 'عاطفي',
    unique: 'فريد',
    creative: 'مبدع',
    adventurous: 'مغامر',
    elegant: 'أنيق',
    loyal: 'مخلص',
    radiant: 'مشرق',
    readyToDiscover: 'جاهز لاكتشاف الأسماء',
    generateBeautifulNames: 'توليد أسماء جميلة',
    fromCulturalTraditions: 'من التقاليد الثقافية',
    meaningfulOrigins: 'أصول ذات معنى',
    meaningfulOriginsDesc: 'أسماء ذات دلالة ثقافية عميقة',
    culturalAuthenticity: 'الأصالة الثقافية',
    culturalAuthenticityDesc: 'أسماء أصيلة من تقاليد حقيقية',
    easyToCopy: 'سهل النسخ والمشاركة',
    easyToCopyDesc: 'وظيفة نسخ ومشاركة بسيطة',
    // Region descriptions
    arabicDesc: 'أسماء عربية تقليدية',
    islamicDesc: 'أسماء إسلامية ومسلمة',
    asianDesc: 'أسماء هندوسية وسنسكريتية وشرقية',
    westernDesc: 'أسماء غربية وأوروبية',
    jewishDesc: 'أسماء يهودية وعبرية',
    africanDesc: 'أسماء أفريقية وقبلية',
    globalDesc: 'أسماء عالمية ودولية',
    latinDesc: 'أسماء لاتينية ومتوسطية',
    northAmericanDesc: 'أسماء أمريكية شمالية',
    europeanDesc: 'أسماء الاتحاد الأوروبي',
    slavicDesc: 'أسماء سلافية وأوروبية شرقية',
    scandinavianDesc: 'أسماء اسكندنافية وشمالية',
    oceanicDesc: 'أسماء أوقيانوسية ومحيطية',
    koreanDesc: 'أسماء كورية وشرق آسيوية',
    japaneseDesc: 'أسماء يابانية وزينية',
    // Region patterns
    arabicPattern: 'تقليدي • ذو معنى • روحي',
    islamicPattern: 'ديني • مبارك • نبيل',
    asianPattern: 'حكمة قديمة • روحي • متناغم',
    westernPattern: 'كلاسيكي • خالد • قوي',
    jewishPattern: 'كتابي • مقدس • تراثي',
    africanPattern: 'قوي • أسلافي • فريد',
    globalPattern: 'عالمي • حديث • متنوع',
    latinPattern: 'رومانسي • شغوف • أنيق',
    northAmericanPattern: 'حديث • مستقل • جريء',
    europeanPattern: 'متحضر • ثقافي • راقي',
    slavicPattern: 'قوي • تقليدي • مرن',
    scandinavianPattern: 'طبيعي • مسالم • قوي',
    oceanicPattern: 'مغامر • حر • طبيعي',
    koreanPattern: 'متناغم • محترم • متوازن',
    japanesePattern: 'بسيط • مسالم • ذو معنى',
    // Gender descriptions
    maleDesc: 'أسماء قوية وذكرية',
    femaleDesc: 'أسماء جميلة وأنثوية',
    unisexDesc: 'أسماء متنوعة ومحايدة',
    // Gender patterns
    malePattern: 'جريء • قوي • تقليدي',
    femalePattern: 'جذاب • جميل • أنيق',
    unisexPattern: 'حديث • متضمن • متنوع',
    // Feeling descriptions
    uniqueDesc: 'أسماء فريدة من نوعها',
    strongDesc: 'أسماء قوية وجريئة',
    beautifulDesc: 'أسماء جميلة ورفيعة',
    wiseDesc: 'أسماء ذكية ومفهومة',
    peacefulDesc: 'أسماء ساكنة وسليمة',
    braveDesc: 'أسماء شجاعة وغير مترددة',
    gentleDesc: 'أسماء ناعمة وطيبة',
    mysteriousDesc: 'أسماء غامضة ومثيرة للاهتمام',
    joyfulDesc: 'أسماء سعيدة وسخية',
    nobleDesc: 'أسماء عظيمة وأخلاقية',
    passionateDesc: 'أسماء عاطفية وقوية',
    creativeDesc: 'أسماء إبداعية وتخيلية',
    adventurousDesc: 'أسماء جريئة ومغامرة',
    elegantDesc: 'أسماء سوفيتة ومصقولة',
    loyalDesc: 'أسماء صادقة ومخلصة',
    radiantDesc: 'أسماء ساطعة ومشرقة',
    // Feeling patterns
    uniquePattern: 'مميز • مذكور • خاص',
    strongPattern: 'قوي • شجاع • متناسق',
    beautifulPattern: 'رفيع • جذاب • مميز',
    wisePattern: 'ذكي • مفهوم • حكيم',
    peacefulPattern: 'ساكن • سليم • متناغم',
    bravePattern: 'غير متردد • جريئ • هرباء',
    gentlePattern: 'ناعم • طيب • ناعم',
    mysteriousPattern: 'غامض • غير مفهوم • مثير للاهتمام',
    joyfulPattern: 'سعيد • سخي • سعيد',
    noblePattern: 'عظيم • أخلاقي • نبيل',
    passionatePattern: 'عاطفي • عاطفي • حار',
    creativePattern: 'إبداعي • تخيلي • إبداعي',
    adventurousPattern: 'جريئ • مغامر • مغامر',
    elegantPattern: 'سوفيت • مصقول • سوفيت',
    loyalPattern: 'صادق • مخلص • صادق',
    radiantPattern: 'ساطع • ساطع • مشرق',
  },
  fr: {
    nameCraft: 'NameCraft', // Keep in English
    discoverNames: 'Découvrez des noms significatifs des cultures du monde entier',
    chooseLanguage: 'Choisissez votre langue',
    getStarted: 'Commencer',
    swipeToContinue: 'Balayez vers le haut ou appuyez pour continuer',
    chooseCategory: 'Choisir une Catégorie',
    selectType: 'Sélectionnez le type de noms que vous recherchez',
    male: 'Masculin',
    female: 'Féminin',
    unisex: 'Unisexe',
    traditionalMasculine: 'Noms masculins traditionnels',
    beautifulFeminine: 'Beaux noms féminins',
    modernNeutral: 'Noms modernes neutres',
    tapCard: 'Appuyez sur une carte pour continuer votre voyage',
    chooseOrigin: 'Choisir l\'Origine',
    selectCultural: 'Sélectionnez l\'origine culturelle pour vos noms',
    names: 'noms',
    chooseFeeling: 'Choisir un Sentiment',
    selectEmotional: 'Sélectionnez l\'essence émotionnelle pour vos noms',
    eachFeeling: 'Chaque sentiment crée un ton émotionnel unique pour vos noms',
    generateNames: 'Générer des Noms',
    fineTune: 'Affinez vos préférences pour des résultats parfaits',
    yourSelection: 'Votre Sélection',
    origin: 'Origine',
    gender: 'Genre',
    culturalOrigin: 'Origine Culturelle',
    numberOfNames: 'Nombre de noms',
    chooseBetween: 'Choisissez entre 1 et 10 noms à générer',
    generateBeautiful: 'Générer de Beaux Noms',
    back: 'Retour',
    next: 'Suivant',
    startOver: 'Recommencer',
    feeling: 'Sentiment',
    // Origins in French
    arabic: 'Arabe',
    islamic: 'Islamique',
    asian: 'Asiatique',
    western: 'Occidental',
    latin: 'Latino-américain',
    northAmerican: 'Nord-américain',
    european: 'Européen',
    african: 'Africain',
    jewish: 'Juif',
    slavic: 'Slave',
    scandinavian: 'Scandinave',
    oceanic: 'Océanique',
    korean: 'Coréen',
    japanese: 'Japonais',
    global: 'Mélange Global',
    // Feelings in French
    strong: 'Fort',
    soft: 'Doux',
    brave: 'Courageux',
    mysterious: 'Mystérieux',
    wise: 'Sage',
    joyful: 'Joyeux',
    noble: 'Noble',
    peaceful: 'Paisible',
    passionate: 'Passionné',
    unique: 'Unique',
    creative: 'Créatif',
    adventurous: 'Aventureux',
    elegant: 'Élégant',
    loyal: 'Loyal',
    radiant: 'Radieux',
    readyToDiscover: 'Prêt à Découvrir des Noms',
    generateBeautifulNames: 'Générer de beaux noms',
    fromCulturalTraditions: 'de traditions culturelles',
    meaningfulOrigins: 'Origines significatives',
    meaningfulOriginsDesc: 'Noms avec une signification culturelle profonde',
    culturalAuthenticity: 'Authenticité culturelle',
    culturalAuthenticityDesc: 'Noms authentiques de vraies traditions',
    easyToCopy: 'Facile à copier et partager',
    easyToCopyDesc: 'Fonctionnalité simple de copie et partage',
    // Region descriptions
    arabicDesc: 'Noms arabes traditionnels',
    islamicDesc: 'Noms islamiques et musulmans',
    asianDesc: 'Noms hindous, sanskrits et orientaux',
    westernDesc: 'Noms occidentaux et européens',
    jewishDesc: 'Noms juifs et hébreux',
    africanDesc: 'Noms africains et tribaux',
    globalDesc: 'Noms globaux et internationaux',
    latinDesc: 'Noms latins et méditerranéens',
    northAmericanDesc: 'Noms nord-américains',
    europeanDesc: 'Noms de l\'Union européenne',
    slavicDesc: 'Noms slaves et est-européens',
    scandinavianDesc: 'Noms scandinaves et nordiques',
    oceanicDesc: 'Noms océaniques et pacifiques',
    koreanDesc: 'Noms coréens et est-asiatiques',
    japaneseDesc: 'Noms japonais et zen',
    // Region patterns
    arabicPattern: 'Traditionnel • Significatif • Spirituel',
    islamicPattern: 'Religieux • Béni • Noble',
    asianPattern: 'Sagesse ancienne • Spirituel • Harmonieux',
    westernPattern: 'Classique • Intemporel • Fort',
    jewishPattern: 'Biblique • Sacré • Héritage',
    africanPattern: 'Puissant • Ancestral • Unique',
    globalPattern: 'Universel • Moderne • Diversifié',
    latinPattern: 'Romantique • Passionné • Élégant',
    northAmericanPattern: 'Moderne • Indépendant • Audacieux',
    europeanPattern: 'Sophistiqué • Culturel • Raffiné',
    slavicPattern: 'Fort • Traditionnel • Résilient',
    scandinavianPattern: 'Naturel • Paisible • Fort',
    oceanicPattern: 'Aventureux • Libre • Naturel',
    koreanPattern: 'Harmonieux • Respectueux • Équilibré',
    japanesePattern: 'Minimaliste • Paisible • Significatif',
    // Gender descriptions
    maleDesc: 'Noms forts et masculins',
    femaleDesc: 'Noms élégants et féminins',
    unisexDesc: 'Noms polyvalents et neutres',
    // Gender patterns
    malePattern: 'Audacieux • Puissant • Traditionnel',
    femalePattern: 'Gracieux • Beau • Élégant',
    unisexPattern: 'Moderne • Inclusif • Polyvalent',
    // Feeling descriptions
    uniqueDesc: 'Noms uniques en leur genre',
    strongDesc: 'Noms puissants et audacieux',
    beautifulDesc: 'Noms élégants et gracieux',
    wiseDesc: 'Noms intelligents et réfléchis',
    peacefulDesc: 'Noms calmes et sereins',
    braveDesc: 'Noms courageux et intrépides',
    gentleDesc: 'Noms doux et tendres',
    mysteriousDesc: 'Noms énigmatiques et intrigants',
    joyfulDesc: 'Noms heureux et joyeux',
    nobleDesc: 'Noms dignes et honorables',
    passionateDesc: 'Noms intenses et émotionnels',
    creativeDesc: 'Noms artistiques et imaginatifs',
    adventurousDesc: 'Noms audacieux et aventureux',
    elegantDesc: 'Noms sophistiqués et raffinés',
    loyalDesc: 'Noms fidèles et dévoués',
    radiantDesc: 'Noms brillants et rayonnants',
    // Feeling patterns
    uniquePattern: 'Distinctif • Mémorable • Spécial',
    strongPattern: 'Puissant • Courageux • Résilient',
    beautifulPattern: 'Gracieux • Beau • Charmant',
    wisePattern: 'Intelligent • Perspicace • Sage',
    peacefulPattern: 'Tranquille • Serein • Harmonieux',
    bravePattern: 'Intrépide • Audacieux • Héroïque',
    gentlePattern: 'Tendre • Gentil • Doux',
    mysteriousPattern: 'Mystérieux • Énigmatique • Intrigant',
    joyfulPattern: 'Heureux • Joyeux • Gai',
    noblePattern: 'Digne • Honorable • Noble',
    passionatePattern: 'Intense • Émotionnel • Ardent',
    creativePattern: 'Artistique • Imaginatif • Créatif',
    adventurousPattern: 'Audacieux • Aventureux • Intrépide',
    elegantPattern: 'Sophistiqué • Raffiné • Élégant',
    loyalPattern: 'Fidèle • Dévoué • Loyal',
    radiantPattern: 'Brillant • Rayonnant • Lumineux',
  },
  es: {
    nameCraft: 'NameCraft', // Keep in English
    discoverNames: 'Descubre nombres significativos de culturas de todo el mundo',
    chooseLanguage: 'Elige tu idioma',
    getStarted: 'Comenzar',
    swipeToContinue: 'Desliza hacia arriba o toca para continuar',
    chooseCategory: 'Elegir Categoría',
    selectType: 'Selecciona el tipo de nombres que buscas',
    male: 'Masculino',
    female: 'Femenino',
    unisex: 'Unisex',
    traditionalMasculine: 'Nombres masculinos tradicionales',
    beautifulFeminine: 'Hermosos nombres femeninos',
    modernNeutral: 'Nombres modernos neutros',
    tapCard: 'Toca una tarjeta para continuar tu viaje',
    chooseOrigin: 'Elegir Origen',
    selectCultural: 'Selecciona el origen cultural para tus nombres',
    names: 'nombres',
    chooseFeeling: 'Elegir Sentimiento',
    selectEmotional: 'Selecciona la esencia emocional para tus nombres',
    eachFeeling: 'Cada sentimiento crea un tono emocional único para tus nombres',
    generateNames: 'Generar Nombres',
    fineTune: 'Ajusta tus preferencias para resultados perfectos',
    yourSelection: 'Tu Selección',
    origin: 'Origen',
    gender: 'Género',
    culturalOrigin: 'Origen Cultural',
    numberOfNames: 'Número de nombres',
    chooseBetween: 'Elige entre 1 y 10 nombres para generar',
    generateBeautiful: 'Generar Nombres Hermosos',
    back: 'Atrás',
    next: 'Siguiente',
    startOver: 'Empezar de Nuevo',
    feeling: 'Sentimiento',
    // Origins in Spanish
    arabic: 'Árabe',
    islamic: 'Islámico',
    asian: 'Asiático',
    western: 'Occidental',
    latin: 'Latinoamericano',
    northAmerican: 'Norteamericano',
    european: 'Europeo',
    african: 'Africano',
    jewish: 'Judío',
    slavic: 'Eslavo',
    scandinavian: 'Escandinavo',
    oceanic: 'Oceánico',
    korean: 'Coreano',
    japanese: 'Japonés',
    global: 'Mezcla Global',
    // Feelings in Spanish
    strong: 'Fuerte',
    soft: 'Suave',
    brave: 'Valiente',
    mysterious: 'Misterioso',
    wise: 'Sabio',
    joyful: 'Alegre',
    noble: 'Noble',
    peaceful: 'Pacífico',
    passionate: 'Apasionado',
    unique: 'Único',
    creative: 'Creativo',
    adventurous: 'Aventurero',
    elegant: 'Elegante',
    loyal: 'Leal',
    radiant: 'Radiante',
    readyToDiscover: 'Listo para Descubrir Nombres',
    generateBeautifulNames: 'Generar nombres hermosos',
    fromCulturalTraditions: 'de tradiciones culturales',
    meaningfulOrigins: 'Orígenes significativos',
    meaningfulOriginsDesc: 'Nombres con profundo significado cultural',
    culturalAuthenticity: 'Autenticidad cultural',
    culturalAuthenticityDesc: 'Nombres auténticos de tradiciones reales',
    easyToCopy: 'Fácil de copiar y compartir',
    easyToCopyDesc: 'Funcionalidad simple de copiar y compartir',
    // Region descriptions
    arabicDesc: 'Nombres árabes tradicionales',
    islamicDesc: 'Nombres islámicos y musulmanes',
    asianDesc: 'Nombres hindúes, sánscritos y orientales',
    westernDesc: 'Nombres occidentales y europeos',
    jewishDesc: 'Nombres judíos y hebreos',
    africanDesc: 'Nombres africanos y tribales',
    globalDesc: 'Nombres globales e internacionales',
    latinDesc: 'Nombres latinos y mediterráneos',
    northAmericanDesc: 'Nombres norteamericanos',
    europeanDesc: 'Nombres de la Unión Europea',
    slavicDesc: 'Nombres eslavos y del este de Europa',
    scandinavianDesc: 'Nombres escandinavos y nórdicos',
    oceanicDesc: 'Nombres oceánicos y del Pacífico',
    koreanDesc: 'Nombres coreanos y del este de Asia',
    japaneseDesc: 'Nombres japoneses y zen',
    // Region patterns
    arabicPattern: 'Tradicional • Significativo • Espiritual',
    islamicPattern: 'Religioso • Bendito • Noble',
    asianPattern: 'Sabiduría antigua • Espiritual • Armonioso',
    westernPattern: 'Clásico • Atemporal • Fuerte',
    jewishPattern: 'Bíblico • Sagrado • Herencia',
    africanPattern: 'Poderoso • Ancestral • Único',
    globalPattern: 'Universal • Moderno • Diverso',
    latinPattern: 'Romántico • Apasionado • Elegante',
    northAmericanPattern: 'Moderno • Independiente • Audaz',
    europeanPattern: 'Sofisticado • Cultural • Refinado',
    slavicPattern: 'Fuerte • Tradicional • Resistente',
    scandinavianPattern: 'Natural • Pacífico • Fuerte',
    oceanicPattern: 'Aventurero • Libre • Natural',
    koreanPattern: 'Armonioso • Respetuoso • Equilibrado',
    japanesePattern: 'Minimalista • Pacífico • Significativo',
    // Gender descriptions
    maleDesc: 'Nombres fuertes y masculinos',
    femaleDesc: 'Nombres elegantes y femeninos',
    unisexDesc: 'Nombres versátiles y neutrales',
    // Gender patterns
    malePattern: 'Audaz • Poderoso • Tradicional',
    femalePattern: 'Gracioso • Hermoso • Elegante',
    unisexPattern: 'Moderno • Inclusivo • Versátil',
    // Feeling descriptions
    uniqueDesc: 'Nombres únicos en su tipo',
    strongDesc: 'Nombres poderosos y audaces',
    beautifulDesc: 'Nombres elegantes y graciosos',
    wiseDesc: 'Nombres inteligentes y reflexivos',
    peacefulDesc: 'Nombres tranquilos y serenos',
    braveDesc: 'Nombres valientes e intrépidos',
    gentleDesc: 'Nombres suaves y tiernos',
    mysteriousDesc: 'Nombres enigmáticos e intrigantes',
    joyfulDesc: 'Nombres felices y alegres',
    nobleDesc: 'Nombres dignos y honorables',
    passionateDesc: 'Nombres intensos y emocionales',
    creativeDesc: 'Nombres artísticos e imaginativos',
    adventurousDesc: 'Nombres audaces y aventureros',
    elegantDesc: 'Nombres sofisticados y refinados',
    loyalDesc: 'Nombres fieles y devotos',
    radiantDesc: 'Nombres brillantes y radiantes',
    // Feeling patterns
    uniquePattern: 'Distintivo • Memorable • Especial',
    strongPattern: 'Poderoso • Valiente • Resistente',
    beautifulPattern: 'Gracioso • Hermoso • Encantador',
    wisePattern: 'Inteligente • Perspicaz • Sabio',
    peacefulPattern: 'Tranquilo • Sereno • Armonioso',
    bravePattern: 'Intrépido • Audaz • Heroico',
    gentlePattern: 'Tierno • Amable • Suave',
    mysteriousPattern: 'Misterioso • Enigmático • Intrigante',
    joyfulPattern: 'Feliz • Alegre • Gozoso',
    noblePattern: 'Digno • Honorable • Noble',
    passionatePattern: 'Intenso • Emocional • Ardiente',
    creativePattern: 'Artístico • Imaginativo • Creativo',
    adventurousPattern: 'Audaz • Aventurero • Intrépido',
    elegantPattern: 'Sofisticado • Refinado • Elegante',
    loyalPattern: 'Fiel • Devoto • Leal',
    radiantPattern: 'Brillante • Radiante • Luminoso',
  },
  ru: {
    nameCraft: 'NameCraft', // Keep in English
    discoverNames: 'Откройте значимые имена из культур всего мира',
    chooseLanguage: 'Выберите язык',
    getStarted: 'Начать',
    swipeToContinue: 'Проведите вверх или нажмите, чтобы продолжить',
    chooseCategory: 'Выбрать Категорию',
    selectType: 'Выберите тип имен, которые вы ищете',
    male: 'Мужской',
    female: 'Женский',
    unisex: 'Унисекс',
    traditionalMasculine: 'Традиционные мужские имена',
    beautifulFeminine: 'Красивые женские имена',
    modernNeutral: 'Современные нейтральные имена',
    tapCard: 'Нажмите на карточку, чтобы продолжить путешествие',
    chooseOrigin: 'Выбрать Происхождение',
    selectCultural: 'Выберите культурное происхождение для ваших имен',
    names: 'имена',
    chooseFeeling: 'Выбрать Чувство',
    selectEmotional: 'Выберите эмоциональную сущность для ваших имен',
    eachFeeling: 'Каждое чувство создает уникальный эмоциональный тон для ваших имен',
    generateNames: 'Генерировать Имена',
    fineTune: 'Настройте ваши предпочтения для идеальных результатов',
    yourSelection: 'Ваш Выбор',
    origin: 'Происхождение',
    gender: 'Пол',
    culturalOrigin: 'Культурное Происхождение',
    numberOfNames: 'Количество имен',
    chooseBetween: 'Выберите от 1 до 10 имен для генерации',
    generateBeautiful: 'Генерировать Красивые Имена',
    back: 'Назад',
    next: 'Далее',
    startOver: 'Начать Заново',
    feeling: 'Чувство',
    // Origins in Russian
    arabic: 'Арабский',
    islamic: 'Исламский',
    asian: 'Азиатский',
    western: 'Западный',
    latin: 'Латиноамериканский',
    northAmerican: 'Североамериканский',
    european: 'Европейский',
    african: 'Африканский',
    jewish: 'Еврейский',
    slavic: 'Славянский',
    scandinavian: 'Скандинавский',
    oceanic: 'Океанический',
    korean: 'Корейский',
    japanese: 'Японский',
    global: 'Глобальная Смесь',
    // Feelings in Russian
    strong: 'Сильный',
    soft: 'Мягкий',
    brave: 'Храбрый',
    mysterious: 'Таинственный',
    wise: 'Мудрый',
    joyful: 'Радостный',
    noble: 'Благородный',
    peaceful: 'Мирный',
    passionate: 'Страстный',
    unique: 'Уникальный',
    creative: 'Творческий',
    adventurous: 'Авантюрный',
    elegant: 'Элегантный',
    loyal: 'Верный',
    radiant: 'Сияющий',
    readyToDiscover: 'Готов Открыть Имена',
    generateBeautifulNames: 'Генерировать красивые имена',
    fromCulturalTraditions: 'из культурных традиций',
    meaningfulOrigins: 'Значимые истоки',
    meaningfulOriginsDesc: 'Имена с глубоким культурным значением',
    culturalAuthenticity: 'Культурная аутентичность',
    culturalAuthenticityDesc: 'Аутентичные имена из реальных традиций',
    easyToCopy: 'Легко копировать и делиться',
    easyToCopyDesc: 'Простая функция копирования и обмена',
    // Region descriptions
    arabicDesc: 'Традиционные арабские имена',
    islamicDesc: 'Исламские и мусульманские имена',
    asianDesc: 'Индуистские, санскритские и восточные имена',
    westernDesc: 'Западные и европейские имена',
    jewishDesc: 'Еврейские и ивритские имена',
    africanDesc: 'Африканские и племенные имена',
    globalDesc: 'Глобальные и международные имена',
    latinDesc: 'Латинские и средиземноморские имена',
    northAmericanDesc: 'Североамериканские имена',
    europeanDesc: 'Имена Европейского Союза',
    slavicDesc: 'Славянские и восточноевропейские имена',
    scandinavianDesc: 'Скандинавские и северные имена',
    oceanicDesc: 'Океанические и тихоокеанские имена',
    koreanDesc: 'Корейские и восточноазиатские имена',
    japaneseDesc: 'Японские и дзенские имена',
    // Region patterns
    arabicPattern: 'Традиционный • Значимый • Духовный',
    islamicPattern: 'Религиозный • Благословенный • Благородный',
    asianPattern: 'Древняя мудрость • Духовный • Гармоничный',
    westernPattern: 'Классический • Вневременной • Сильный',
    jewishPattern: 'Библейский • Священный • Наследие',
    africanPattern: 'Мощный • Родовой • Уникальный',
    globalPattern: 'Универсальный • Современный • Разнообразный',
    latinPattern: 'Романтичный • Страстный • Элегантный',
    northAmericanPattern: 'Современный • Независимый • Смелый',
    europeanPattern: 'Утонченный • Культурный • Изысканный',
    slavicPattern: 'Сильный • Традиционный • Устойчивый',
    scandinavianPattern: 'Природный • Мирный • Сильный',
    oceanicPattern: 'Авантюрный • Свободный • Естественный',
    koreanPattern: 'Гармоничный • Уважительный • Сбалансированный',
    japanesePattern: 'Минималистичный • Мирный • Значимый',
    // Gender descriptions
    maleDesc: 'Сильные, мужественные имена',
    femaleDesc: 'Элегантные, женственные имена',
    unisexDesc: 'Универсальные, нейтральные имена',
    // Gender patterns
    malePattern: 'Смелый • Мощный • Традиционный',
    femalePattern: 'Грациозный • Красивый • Элегантный',
    unisexPattern: 'Современный • Инклюзивный • Универсальный',
    // Feeling descriptions
    uniqueDesc: 'Имена, которые не повторяются',
    strongDesc: 'Сильные и смелые имена',
    beautifulDesc: 'Элегантные и изящные имена',
    wiseDesc: 'Умные и размышляющие имена',
    peacefulDesc: 'Спокойные и умиротворенные имена',
    braveDesc: 'Храбрые и смелые имена',
    gentleDesc: 'Мягкие и ласковые имена',
    mysteriousDesc: 'Загадочные и захватывающие имена',
    joyfulDesc: 'Счастливые и веселые имена',
    nobleDesc: 'Доброродные и достойные имена',
    passionateDesc: 'Эмоциональные и страстные имена',
    creativeDesc: 'Творческие и воображаемые имена',
    adventurousDesc: 'Смелые и смелые имена',
    elegantDesc: 'Сложносочиненные и изысканные имена',
    loyalDesc: 'Верные и преданные имена',
    radiantDesc: 'Сияющие и сияющие имена',
    // Feeling patterns
    uniquePattern: 'Уникальный • Запоминающийся • Специальный',
    strongPattern: 'Могучий • Смелый • Устойчивый',
    beautifulPattern: 'Грациозный • Красивый • Харизматичный',
    wisePattern: 'Умный • Проницательный • Мудрый',
    peacefulPattern: 'Транквильный • Спокойный • Гармоничный',
    bravePattern: 'Безбоязненный • Смелый • Героический',
    gentlePattern: 'Нягкий • Добрый • Нягкий',
    mysteriousPattern: 'Загадочный • Удивительный • Захватывающий',
    joyfulPattern: 'Счастливый • Веселый • Радостный',
    noblePattern: 'Доброродный • Достойный • Благородный',
    passionatePattern: 'Страстный • Эмоциональный • Огненный',
    creativePattern: 'Творческий • Воображаемый • Креативный',
    adventurousPattern: 'Смелый • Смелый • Авантюрный',
    elegantPattern: 'Сложносочиненный • Изысканный • Элегантный',
    loyalPattern: 'Верный • Преданный • Верный',
    radiantPattern: 'Светящийся • Сияющий • Радиантный',
  },
  de: {
    nameCraft: 'NameCraft', // Keep in English
    discoverNames: 'Entdecken Sie bedeutungsvolle Namen aus Kulturen der ganzen Welt',
    chooseLanguage: 'Wählen Sie Ihre Sprache',
    getStarted: 'Loslegen',
    swipeToContinue: 'Nach oben wischen oder tippen zum Fortfahren',
    chooseCategory: 'Kategorie Wählen',
    selectType: 'Wählen Sie den Typ der Namen, nach denen Sie suchen',
    male: 'Männlich',
    female: 'Weiblich',
    unisex: 'Unisex',
    traditionalMasculine: 'Traditionelle männliche Namen',
    beautifulFeminine: 'Schöne weibliche Namen',
    modernNeutral: 'Moderne geschlechtsneutrale Namen',
    tapCard: 'Tippen Sie auf eine Karte, um Ihre Reise fortzusetzen',
    chooseOrigin: 'Herkunft Wählen',
    selectCultural: 'Wählen Sie die kulturelle Herkunft für Ihre',
    names: 'Namen',
    chooseFeeling: 'Gefühl Wählen',
    selectEmotional: 'Wählen Sie die emotionale Essenz für Ihre Namen',
    eachFeeling: 'Jedes Gefühl schafft einen einzigartigen emotionalen Ton für Ihre Namen',
    generateNames: 'Namen Generieren',
    fineTune: 'Verfeinern Sie Ihre Präferenzen für perfekte Ergebnisse',
    yourSelection: 'Ihre Auswahl',
    origin: 'Herkunft',
    gender: 'Geschlecht',
    culturalOrigin: 'Kulturelle Herkunft',
    numberOfNames: 'Anzahl der Namen',
    chooseBetween: 'Wählen Sie zwischen 1 und 10 Namen zur Generierung',
    generateBeautiful: 'Schöne Namen Generieren',
    back: 'Zurück',
    next: 'Weiter',
    startOver: 'Neu Beginnen',
    feeling: 'Gefühl',
    // Origins in German
    arabic: 'Arabisch',
    islamic: 'Islamisch',
    asian: 'Asiatisch',
    western: 'Westlich',
    latin: 'Lateinamerikanisch',
    northAmerican: 'Nordamerikanisch',
    european: 'Europäisch',
    african: 'Afrikanisch',
    jewish: 'Jüdisch',
    slavic: 'Slawisch',
    scandinavian: 'Skandinavisch',
    oceanic: 'Ozeanisch',
    korean: 'Koreanisch',
    japanese: 'Japanisch',
    global: 'Globale Mischung',
    // Feelings in German
    strong: 'Stark',
    soft: 'Sanft',
    brave: 'Mutig',
    mysterious: 'Geheimnisvoll',
    wise: 'Weise',
    joyful: 'Freudig',
    noble: 'Edel',
    peaceful: 'Friedlich',
    passionate: 'Leidenschaftlich',
    unique: 'Einzigartig',
    creative: 'Kreativ',
    adventurous: 'Abenteuerlich',
    elegant: 'Elegant',
    loyal: 'Loyal',
    radiant: 'Strahlend',
    readyToDiscover: 'Bereit Namen zu Entdecken',
    generateBeautifulNames: 'Schöne Namen generieren',
    fromCulturalTraditions: 'aus kulturellen Traditionen',
    meaningfulOrigins: 'Bedeutungsvolle Ursprünge',
    meaningfulOriginsDesc: 'Namen mit tiefer kultureller Bedeutung',
    culturalAuthenticity: 'Kulturelle Authentizität',
    culturalAuthenticityDesc: 'Authentische Namen aus echten Traditionen',
    easyToCopy: 'Einfach zu kopieren und teilen',
    easyToCopyDesc: 'Einfache Kopier- und Teilen-Funktionalität',
    // Additional keys for NameDisplay
    creatingNames: 'Ihre perfekten Namen erstellen',
    craftingNames: 'Bedeutungsvolle Namen mit kultureller Tiefe erstellen...',
    weavingMagic: 'Kulturelle Magie in jeden Namen weben',
    yourBeautifulNames: 'Ihre schönen Namen',
    tradition: 'Tradition',
    copied: 'Kopiert!',
    copyAll: 'Alle kopieren',
    generateMore: 'Mehr generieren',
    // Region descriptions
    arabicDesc: 'Traditionelle arabische Namen',
    islamicDesc: 'Islamische und muslimische Namen',
    asianDesc: 'Hinduistische, Sanskrit- und östliche Namen',
    westernDesc: 'Westliche und europäische Namen',
    jewishDesc: 'Jüdische und hebräische Namen',
    africanDesc: 'Afrikanische und Stammesnamen',
    globalDesc: 'Globale und internationale Namen',
    latinDesc: 'Lateinische und mediterrane Namen',
    northAmericanDesc: 'Nordamerikanische Namen',
    europeanDesc: 'Namen der Europäischen Union',
    slavicDesc: 'Slawische und osteuropäische Namen',
    scandinavianDesc: 'Skandinavische und nordische Namen',
    oceanicDesc: 'Ozeanische und pazifische Namen',
    koreanDesc: 'Koreanische und ostasiatische Namen',
    japaneseDesc: 'Japanische und Zen-Namen',
    // Region patterns
    arabicPattern: 'Traditionell • Bedeutungsvoll • Spirituell',
    islamicPattern: 'Religiös • Gesegnet • Edel',
    asianPattern: 'Alte Weisheit • Spirituell • Harmonisch',
    westernPattern: 'Klassisch • Zeitlos • Stark',
    jewishPattern: 'Biblisch • Heilig • Erbe',
    africanPattern: 'Mächtig • Ahnen • Einzigartig',
    globalPattern: 'Universal • Modern • Vielfältig',
    latinPattern: 'Romantisch • Leidenschaftlich • Elegant',
    northAmericanPattern: 'Modern • Unabhängig • Mutig',
    europeanPattern: 'Raffiniert • Kulturell • Verfeinert',
    slavicPattern: 'Stark • Traditionell • Widerstandsfähig',
    scandinavianPattern: 'Natürlich • Friedlich • Stark',
    oceanicPattern: 'Abenteuerlich • Frei • Natürlich',
    koreanPattern: 'Harmonisch • Respektvoll • Ausgewogen',
    japanesePattern: 'Minimalistisch • Friedlich • Bedeutungsvoll',
    // Gender descriptions
    maleDesc: 'Starke, männliche Namen',
    femaleDesc: 'Elegante, weibliche Namen',
    unisexDesc: 'Vielseitige, geschlechtsneutrale Namen',
    // Gender patterns
    malePattern: 'Mutig • Mächtig • Traditionell',
    femalePattern: 'Anmutig • Schön • Elegant',
    unisexPattern: 'Modern • Inklusiv • Vielseitig',
    // Feeling descriptions
    uniqueDesc: 'Einzigartige Namen',
    strongDesc: 'Mächtige und mutige Namen',
    beautifulDesc: 'Elegante und anmutige Namen',
    wiseDesc: 'Intelligente und nachdenkliche Namen',
    peacefulDesc: 'Ruhige und friedliche Namen',
    braveDesc: 'Mutige und furchtlose Namen',
    gentleDesc: 'Sanfte und zarte Namen',
    mysteriousDesc: 'Rätselhafte und faszinierende Namen',
    joyfulDesc: 'Glückliche und fröhliche Namen',
    nobleDesc: 'Würdige und ehrenvolle Namen',
    passionateDesc: 'Intensive und emotionale Namen',
    creativeDesc: 'Künstlerische und fantasievolle Namen',
    adventurousDesc: 'Mutige und wagemutige Namen',
    elegantDesc: 'Sofistizierte und raffinierte Namen',
    loyalDesc: 'Treue und hingebungsvolle Namen',
    radiantDesc: 'Helle und strahlende Namen',
    // Feeling patterns
    uniquePattern: 'Unterscheidend • Denkwürdig • Besonders',
    strongPattern: 'Mächtig • Mutig • Widerstandsfähig',
    beautifulPattern: 'Anmutig • Lieblich • Charmant',
    wisePattern: 'Intelligent • Einsichtsvoll • Weise',
    peacefulPattern: 'Ruhig • Friedlich • Harmonisch',
    bravePattern: 'Furchtlos • Mutig • Heroisch',
    gentlePattern: 'Zart • Freundlich • Sanft',
    mysteriousPattern: 'Geheimnisvoll • Rätselhaft • Faszinierend',
    joyfulPattern: 'Glücklich • Fröhlich • Freudig',
    noblePattern: 'Würdig • Ehrenvoll • Edel',
    passionatePattern: 'Intensiv • Emotional • Feurig',
    creativePattern: 'Künstlerisch • Fantasievoll • Kreativ',
    adventurousPattern: 'Mutig • Wagemutig • Abenteuerlich',
    elegantPattern: 'Sofistiziert • Raffiniert • Elegant',
    loyalPattern: 'Treu • Hingebungsvoll • Loyal',
    radiantPattern: 'Hell • Strahlend • Leuchtend',
  },
  ja: {
    nameCraft: 'NameCraft', // Keep in English
    discoverNames: '世界中の文化から意味のある名前を発見する',
    chooseLanguage: '言語を選択',
    getStarted: '始める',
    swipeToContinue: '上にスワイプまたはタップして続行',
    chooseCategory: 'カテゴリを選択',
    selectType: '探している名前のタイプを選択してください',
    male: '男性',
    female: '女性',
    unisex: 'ユニセックス',
    traditionalMasculine: '伝統的な男性名',
    beautifulFeminine: '美しい女性名',
    modernNeutral: '現代的な中性名',
    tapCard: 'カードをタップして旅を続ける',
    chooseOrigin: '起源を選択',
    selectCultural: 'あなたの名前の文化的起源を選択してください',
    names: '名前',
    chooseFeeling: '感情を選択',
    selectEmotional: 'あなたの名前の感情的な本質を選択してください',
    eachFeeling: '各感情はあなたの名前に独特な感情的なトーンを作ります',
    generateNames: '名前を生成',
    fineTune: '完璧な結果のために好みを微調整',
    yourSelection: 'あなたの選択',
    origin: '起源',
    gender: '性別',
    culturalOrigin: '文化的起源',
    numberOfNames: '名前の数',
    chooseBetween: '生成する名前を1から10の間で選択',
    generateBeautiful: '美しい名前を生成',
    back: '戻る',
    next: '次へ',
    startOver: '最初から始める',
    feeling: '感情',
    // Origins in Japanese
    arabic: 'アラビア',
    islamic: 'イスラム',
    asian: 'アジア',
    western: '西洋',
    latin: 'ラテンアメリカ',
    northAmerican: '北米',
    european: 'ヨーロッパ',
    african: 'アフリカ',
    jewish: 'ユダヤ',
    slavic: 'スラブ',
    scandinavian: 'スカンジナビア',
    oceanic: 'オセアニア',
    korean: '韓国',
    japanese: '日本',
    global: 'グローバルミックス',
    // Feelings in Japanese
    strong: '強い',
    soft: '優しい',
    brave: '勇敢',
    mysterious: '神秘的',
    wise: '賢い',
    joyful: '喜びに満ちた',
    noble: '高貴',
    peaceful: '平和',
    passionate: '情熱的',
    unique: 'ユニーク',
    creative: '創造的',
    adventurous: '冒険的',
    elegant: 'エレガント',
    loyal: '忠実',
    radiant: '輝く',
    readyToDiscover: '名前を発見する準備完了',
    generateBeautifulNames: '美しい名前',
    fromCulturalTraditions: '文化的伝統から',
    meaningfulOrigins: '意味のある起源',
    meaningfulOriginsDesc: '深い文化的意味を持つ名前',
    culturalAuthenticity: '文化的真実性',
    culturalAuthenticityDesc: '真の伝統からの本物の名前',
    easyToCopy: 'コピーと共有が簡単',
    easyToCopyDesc: 'シンプルなコピーと共有機能',
  },
  zh: {
    nameCraft: 'NameCraft', // Keep in English
    discoverNames: '发现来自世界各地文化的有意义名字',
    chooseLanguage: '选择您的语言',
    getStarted: '开始',
    swipeToContinue: '向上滑动或点击继续',
    chooseCategory: '选择类别',
    selectType: '选择您要寻找的名字类型',
    male: '男性',
    female: '女性',
    unisex: '中性',
    traditionalMasculine: '传统男性名字',
    beautifulFeminine: '美丽女性名字',
    modernNeutral: '现代中性名字',
    tapCard: '点击卡片继续您的旅程',
    chooseOrigin: '选择起源',
    selectCultural: '为您的名字选择文化起源',
    names: '名字',
    chooseFeeling: '选择感觉',
    selectEmotional: '为您的名字选择情感本质',
    eachFeeling: '每种感觉为您的名字创造独特的情感色调',
    generateNames: '生成名字',
    fineTune: '微调您的偏好以获得完美结果',
    yourSelection: '您的选择',
    origin: '起源',
    gender: '性别',
    culturalOrigin: '文化起源',
    numberOfNames: '名字数量',
    chooseBetween: '选择生成1到10个名字',
    generateBeautiful: '生成美丽名字',
    back: '返回',
    next: '下一步',
    startOver: '重新开始',
    feeling: '感觉',
    // Origins in Chinese
    arabic: '阿拉伯',
    islamic: '伊斯兰',
    asian: '亚洲',
    western: '西方',
    latin: '拉丁美洲',
    northAmerican: '北美',
    european: '欧洲',
    african: '非洲',
    jewish: '犹太',
    slavic: '斯拉夫',
    scandinavian: '斯堪的纳维亚',
    oceanic: '大洋洲',
    korean: '韩国',
    japanese: '日本',
    global: '全球混合',
    // Feelings in Chinese
    strong: '强壮',
    soft: '温柔',
    brave: '勇敢',
    mysterious: '神秘',
    wise: '智慧',
    joyful: '快乐',
    noble: '高贵',
    peaceful: '和平',
    passionate: '热情',
    unique: '独特',
    creative: '创意',
    adventurous: '冒险',
    elegant: '优雅',
    loyal: '忠诚',
    radiant: '光芒四射',
    readyToDiscover: '准备发现名字',
    generateBeautifulNames: '生成美丽的名字',
    fromCulturalTraditions: '来自文化传统',
    meaningfulOrigins: '有意义的起源',
    meaningfulOriginsDesc: '具有深刻文化意义的名字',
    culturalAuthenticity: '文化真实性',
    culturalAuthenticityDesc: '来自真实传统的真实名字',
    easyToCopy: '易于复制和分享',
    easyToCopyDesc: '简单的复制和分享功能',
  },
  hi: {
    nameCraft: 'NameCraft', // Keep in English
    discoverNames: 'दुनिया भर की संस्कृतियों से सार्थक नामों की खोज करें',
    chooseLanguage: 'अपनी भाषा चुनें',
    getStarted: 'शुरू करें',
    swipeToContinue: 'जारी रखने के लिए ऊपर स्वाइप करें या टैप करें',
    chooseCategory: 'श्रेणी चुनें',
    selectType: 'आप जिस प्रकार के नाम खोज रहे हैं उसे चुनें',
    male: 'पुरुष',
    female: 'महिला',
    unisex: 'यूनिसेक्स',
    traditionalMasculine: 'पारंपरिक पुरुष नाम',
    beautifulFeminine: 'सुंदर महिला नाम',
    modernNeutral: 'आधुनिक तटस्थ नाम',
    tapCard: 'अपनी यात्रा जारी रखने के लिए एक कार्ड पर टैप करें',
    chooseOrigin: 'मूल चुनें',
    selectCultural: 'अपने नामों के लिए सांस्कृतिक मूल चुनें',
    names: 'नाम',
    chooseFeeling: 'भावना चुनें',
    selectEmotional: 'अपने नामों के लिए भावनात्मक सार चुनें',
    eachFeeling: 'हर भावना आपके नामों के लिए एक अनोखा भावनात्मक स्वर बनाती है',
    generateNames: 'नाम जेनरेट करें',
    fineTune: 'सही परिणामों के लिए अपनी प्राथमिकताओं को बेहतर बनाएं',
    yourSelection: 'आपका चयन',
    origin: 'मूल',
    gender: 'लिंग',
    culturalOrigin: 'सांस्कृतिक मूल',
    numberOfNames: 'नामों की संख्या',
    chooseBetween: 'जेनरेट करने के लिए 1 से 10 नामों के बीच चुनें',
    generateBeautiful: 'सुंदर नाम जेनरेट करें',
    back: 'वापस',
    next: 'अगला',
    startOver: 'फिर से शुरू करें',
    feeling: 'भावना',
    // Origins in Hindi
    arabic: 'अरबी',
    islamic: 'इस्लामी',
    asian: 'एशियाई',
    western: 'पश्चिमी',
    latin: 'लैटिन अमेरिकी',
    northAmerican: 'उत्तर अमेरिकी',
    european: 'यूरोपीय',
    african: 'अफ्रीकी',
    jewish: 'यहूदी',
    slavic: 'स्लाविक',
    scandinavian: 'स्कैंडिनेवियाई',
    oceanic: 'ओशिनिक',
    korean: 'कोरियाई',
    japanese: 'जापानी',
    global: 'ग्लोबल मिक्स',
    // Feelings in Hindi
    strong: 'मजबूत',
    soft: 'कोमल',
    brave: 'बहादुर',
    mysterious: 'रहस्यमय',
    wise: 'बुद्धिमान',
    joyful: 'खुशमिजाज',
    noble: 'कुलीन',
    peaceful: 'शांतिप्रिय',
    passionate: 'भावुक',
    unique: 'अनोखा',
    creative: 'रचनात्मक',
    adventurous: 'साहसिक',
    elegant: 'सुरुचिपूर्ण',
    loyal: 'वफादार',
    radiant: 'तेजस्वी',
    readyToDiscover: 'नाम खोजने के लिए तैयार',
    generateBeautifulNames: 'सुंदर नाम उत्पन्न करें',
    fromCulturalTraditions: 'सांस्कृतिक परंपराओं से',
    meaningfulOrigins: 'सार्थक मूल',
    meaningfulOriginsDesc: 'गहरे सांस्कृतिक महत्व वाले नाम',
    culturalAuthenticity: 'सांस्कृतिक प्रामाणिकता',
    culturalAuthenticityDesc: 'वास्तविक परंपराओं से प्रामाणिक नाम',
    easyToCopy: 'कॉपी और शेयर करने में आसान',
    easyToCopyDesc: 'सरल कॉपी और शेयर कार्यक्षमता',
  }
};

const useNameStore = create(
  persist(
    (set, get) => ({
      // Theme state - Default to dark for premium feel
      isDarkMode: true,
      toggleDarkMode: () => set((state) => ({ isDarkMode: !state.isDarkMode })),

      // Wizard flow state
      currentStep: 'landing', // 'landing', 'gender', 'region', 'feeling', 'generator'
      selectedLanguage: 'en',
      selectedGender: null, // 'male', 'female', 'unisex'
      selectedRegion: null, // 'arabic', 'islamic', 'asian', 'western', etc.
      selectedFeeling: null, // 'strong', 'soft', 'brave', 'mysterious', etc.
      
      // Translation helper
      t: (key) => {
        const state = get();
        return translations[state.selectedLanguage]?.[key] || translations.en[key] || key;
      },
      
      // Navigation
      setStep: (step) => set({ currentStep: step }),
      setLanguage: (language) => set({ selectedLanguage: language }),
      setGender: (gender) => set({ selectedGender: gender }),
      setRegion: (region) => set({ selectedRegion: region }),
      setFeeling: (feeling) => set({ selectedFeeling: feeling }),

      // Filter state (legacy - keeping for compatibility)
      filters: {
        gender: '',
        culture: '',
        count: 5, // Default to 5 names, max 10
      },
      setFilters: (newFilters) =>
        set((state) => ({
          filters: { ...state.filters, ...newFilters },
        })),

      // Generated names
      generatedNames: [],
      setGeneratedNames: (names) => set({ generatedNames: names }),

      // UI state
      isGenerating: false,
      setIsGenerating: (loading) => set({ isGenerating: loading }),

      // Animation state
      isTransitioning: false,
      setIsTransitioning: (transitioning) => set({ isTransitioning: transitioning }),

      // Last generation timestamp
      lastGenerated: null,
      setLastGenerated: () => set({ lastGenerated: Date.now() }),

      // Navigation methods
      goToGenderSelection: () => {
        set({ isTransitioning: true });
        setTimeout(() => {
          set({ currentStep: 'gender', isTransitioning: false });
        }, 200); // Reduced delay for smoother transitions
      },

      goToRegionSelection: (gender) => {
        set({ selectedGender: gender, isTransitioning: true });
        setTimeout(() => {
          set({ currentStep: 'region', isTransitioning: false });
        }, 400); // Reduced delay
      },

      goToFeelingSelection: (region) => {
        set({ selectedRegion: region, isTransitioning: true });
        setTimeout(() => {
          set({ currentStep: 'feeling', isTransitioning: false });
        }, 400); // New feeling selection step
      },

      goToGenerator: (feeling) => {
        set({ selectedFeeling: feeling, isTransitioning: true });
        setTimeout(() => {
          set({ currentStep: 'generator', isTransitioning: false });
        }, 400);
      },

      // Go back methods
      goBack: () => {
        const currentStep = get().currentStep;
        set({ isTransitioning: true });
        setTimeout(() => {
          switch (currentStep) {
            case 'gender':
              set({ currentStep: 'landing', isTransitioning: false });
              break;
            case 'region':
              set({ currentStep: 'gender', isTransitioning: false });
              break;
            case 'feeling':
              set({ currentStep: 'region', isTransitioning: false });
              break;
            case 'generator':
              set({ currentStep: 'feeling', isTransitioning: false });
              break;
            default:
              set({ isTransitioning: false });
          }
        }, 300);
      },

      // Reset wizard
      resetWizard: () => set({
        currentStep: 'landing',
        selectedLanguage: 'en',
        selectedGender: null,
        selectedRegion: null,
        selectedFeeling: null,
        generatedNames: [],
        lastGenerated: null,
        isTransitioning: false,
      }),

      // Clear all data
      clearData: () =>
        set({
          generatedNames: [],
          lastGenerated: null,
          filters: { gender: '', culture: '', count: 5 },
        }),
    }),
    {
      name: 'name-generator-storage',
      partialize: (state) => ({ 
        isDarkMode: state.isDarkMode, 
        selectedLanguage: state.selectedLanguage,
        filters: state.filters 
      }),
    }
  )
);

export default useNameStore; 