import { create } from 'zustand';
import { persist } from 'zustand/middleware';

// Comprehensive translations for different languages
const translations = {
  en: {
    nameCraft: 'NameCraft', // Keep in English for all languages
    discoverNames: 'Discover meaningful names from cultures around the world',
    chooseLanguage: 'Choose your language',
    getStarted: 'Get Started',
    swipeToContinue: 'Swipe up or tap to continue',
    chooseCategory: 'Choose Category',
    selectType: 'Select the type of names you\'re looking for',
    male: 'Male',
    female: 'Female',
    unisex: 'Unisex',
    traditionalMasculine: 'Traditional masculine names',
    beautifulFeminine: 'Beautiful feminine names',
    modernNeutral: 'Modern gender-neutral names',
    tapCard: 'Tap a card to continue your journey',
    chooseOrigin: 'Choose Origin',
    selectCultural: 'Select the cultural origin for your',
    names: 'names',
    chooseFeeling: 'Choose Feeling',
    selectEmotional: 'Select the emotional essence for your names',
    eachFeeling: 'Each feeling creates a unique emotional tone for your names',
    generateNames: 'Generate Names',
    fineTune: 'Fine-tune your preferences for perfect results',
    yourSelection: 'Your Selection',
    origin: 'Origin',
    gender: 'Gender',
    culturalOrigin: 'Cultural Origin',
    numberOfNames: 'Number of names',
    chooseBetween: 'Choose between 1 and 10 names to generate',
    generateBeautiful: 'Generate Beautiful Names',
    back: 'Back',
    next: 'Next',
    startOver: 'Start Over',
    feeling: 'Feeling',
    // Origins
    arabic: 'Arabic',
    islamic: 'Islamic',
    asian: 'Asian',
    western: 'Western',
    latin: 'Latin American',
    northAmerican: 'North American',
    european: 'European',
    african: 'African',
    jewish: 'Jewish',
    slavic: 'Slavic',
    scandinavian: 'Scandinavian',
    oceanic: 'Oceanic',
    korean: 'Korean',
    japanese: 'Japanese',
    global: 'Global Mix',
    // Feelings
    strong: 'Strong',
    soft: 'Soft',
    brave: 'Brave',
    mysterious: 'Mysterious',
    wise: 'Wise',
    joyful: 'Joyful',
    noble: 'Noble',
    peaceful: 'Peaceful',
    passionate: 'Passionate',
    unique: 'Unique',
    creative: 'Creative',
    adventurous: 'Adventurous',
    elegant: 'Elegant',
    loyal: 'Loyal',
    radiant: 'Radiant',
    readyToDiscover: 'Ready to Discover Names',
    generateBeautifulNames: 'Generate beautiful names',
    fromCulturalTraditions: 'from cultural traditions',
    meaningfulOrigins: 'Meaningful origins',
    meaningfulOriginsDesc: 'Names with deep cultural significance',
    culturalAuthenticity: 'Cultural authenticity',
    culturalAuthenticityDesc: 'Authentic names from real traditions',
    easyToCopy: 'Easy to copy & share',
    easyToCopyDesc: 'Simple copy and share functionality',
  },
  ar: {
    nameCraft: 'NameCraft', // Keep in English
    discoverNames: 'اكتشف أسماء ذات معنى من ثقافات حول العالم',
    chooseLanguage: 'اختر لغتك',
    getStarted: 'ابدأ',
    swipeToContinue: 'اسحب لأعلى أو اضغط للمتابعة',
    chooseCategory: 'اختر الفئة',
    selectType: 'اختر نوع الأسماء التي تبحث عنها',
    male: 'ذكر',
    female: 'أنثى',
    unisex: 'للجنسين',
    traditionalMasculine: 'أسماء ذكورية تقليدية',
    beautifulFeminine: 'أسماء أنثوية جميلة',
    modernNeutral: 'أسماء حديثة محايدة',
    tapCard: 'اضغط على البطاقة لمتابعة رحلتك',
    chooseOrigin: 'اختر الأصل',
    selectCultural: 'اختر الأصل الثقافي لأسمائك',
    names: 'أسماء',
    chooseFeeling: 'اختر المشاعر',
    selectEmotional: 'اختر الجوهر العاطفي لأسمائك',
    eachFeeling: 'كل شعور يخلق نبرة عاطفية فريدة لأسمائك',
    generateNames: 'إنشاء الأسماء',
    fineTune: 'اضبط تفضيلاتك للحصول على نتائج مثالية',
    yourSelection: 'اختيارك',
    origin: 'الأصل',
    gender: 'الجنس',
    culturalOrigin: 'الأصل الثقافي',
    numberOfNames: 'عدد الأسماء',
    chooseBetween: 'اختر بين 1 و 10 أسماء للإنشاء',
    generateBeautiful: 'إنشاء أسماء جميلة',
    back: 'رجوع',
    next: 'التالي',
    startOver: 'ابدأ من جديد',
    feeling: 'المشاعر',
    // Origins in Arabic
    arabic: 'عربي',
    islamic: 'إسلامي',
    asian: 'آسيوي',
    western: 'غربي',
    latin: 'أمريكا اللاتينية',
    northAmerican: 'أمريكا الشمالية',
    european: 'أوروبي',
    african: 'أفريقي',
    jewish: 'يهودي',
    slavic: 'سلافي',
    scandinavian: 'إسكندنافي',
    oceanic: 'المحيط الهادئ',
    korean: 'كوري',
    japanese: 'ياباني',
    global: 'مزيج عالمي',
    // Feelings in Arabic
    strong: 'قوي',
    soft: 'لطيف',
    brave: 'شجاع',
    mysterious: 'غامض',
    wise: 'حكيم',
    joyful: 'مبهج',
    noble: 'نبيل',
    peaceful: 'مسالم',
    passionate: 'عاطفي',
    unique: 'فريد',
    creative: 'مبدع',
    adventurous: 'مغامر',
    elegant: 'أنيق',
    loyal: 'مخلص',
    radiant: 'مشرق',
    readyToDiscover: 'جاهز لاكتشاف الأسماء',
    generateBeautifulNames: 'توليد أسماء جميلة',
    fromCulturalTraditions: 'من التقاليد الثقافية',
    meaningfulOrigins: 'أصول ذات معنى',
    meaningfulOriginsDesc: 'أسماء ذات دلالة ثقافية عميقة',
    culturalAuthenticity: 'الأصالة الثقافية',
    culturalAuthenticityDesc: 'أسماء أصيلة من تقاليد حقيقية',
    easyToCopy: 'سهل النسخ والمشاركة',
    easyToCopyDesc: 'وظيفة نسخ ومشاركة بسيطة',
  },
  fr: {
    nameCraft: 'NameCraft', // Keep in English
    discoverNames: 'Découvrez des noms significatifs des cultures du monde entier',
    chooseLanguage: 'Choisissez votre langue',
    getStarted: 'Commencer',
    swipeToContinue: 'Balayez vers le haut ou appuyez pour continuer',
    chooseCategory: 'Choisir une Catégorie',
    selectType: 'Sélectionnez le type de noms que vous recherchez',
    male: 'Masculin',
    female: 'Féminin',
    unisex: 'Unisexe',
    traditionalMasculine: 'Noms masculins traditionnels',
    beautifulFeminine: 'Beaux noms féminins',
    modernNeutral: 'Noms modernes neutres',
    tapCard: 'Appuyez sur une carte pour continuer votre voyage',
    chooseOrigin: 'Choisir l\'Origine',
    selectCultural: 'Sélectionnez l\'origine culturelle pour vos noms',
    names: 'noms',
    chooseFeeling: 'Choisir un Sentiment',
    selectEmotional: 'Sélectionnez l\'essence émotionnelle pour vos noms',
    eachFeeling: 'Chaque sentiment crée un ton émotionnel unique pour vos noms',
    generateNames: 'Générer des Noms',
    fineTune: 'Affinez vos préférences pour des résultats parfaits',
    yourSelection: 'Votre Sélection',
    origin: 'Origine',
    gender: 'Genre',
    culturalOrigin: 'Origine Culturelle',
    numberOfNames: 'Nombre de noms',
    chooseBetween: 'Choisissez entre 1 et 10 noms à générer',
    generateBeautiful: 'Générer de Beaux Noms',
    back: 'Retour',
    next: 'Suivant',
    startOver: 'Recommencer',
    feeling: 'Sentiment',
    // Origins in French
    arabic: 'Arabe',
    islamic: 'Islamique',
    asian: 'Asiatique',
    western: 'Occidental',
    latin: 'Latino-américain',
    northAmerican: 'Nord-américain',
    european: 'Européen',
    african: 'Africain',
    jewish: 'Juif',
    slavic: 'Slave',
    scandinavian: 'Scandinave',
    oceanic: 'Océanique',
    korean: 'Coréen',
    japanese: 'Japonais',
    global: 'Mélange Global',
    // Feelings in French
    strong: 'Fort',
    soft: 'Doux',
    brave: 'Courageux',
    mysterious: 'Mystérieux',
    wise: 'Sage',
    joyful: 'Joyeux',
    noble: 'Noble',
    peaceful: 'Paisible',
    passionate: 'Passionné',
    unique: 'Unique',
    creative: 'Créatif',
    adventurous: 'Aventureux',
    elegant: 'Élégant',
    loyal: 'Loyal',
    radiant: 'Radieux',
    readyToDiscover: 'Prêt à Découvrir des Noms',
    generateBeautiful: 'Générer de beaux',
    names: 'noms',
    from: 'de',
    culturalTraditions: 'traditions culturelles',
    meaningfulOrigins: 'Origines significatives',
    meaningfulOriginsDesc: 'Noms avec une signification culturelle profonde',
    culturalAuthenticity: 'Authenticité culturelle',
    culturalAuthenticityDesc: 'Noms authentiques de vraies traditions',
    easyToCopy: 'Facile à copier et partager',
    easyToCopyDesc: 'Fonctionnalité simple de copie et partage',
  },
  es: {
    nameCraft: 'NameCraft', // Keep in English
    discoverNames: 'Descubre nombres significativos de culturas de todo el mundo',
    chooseLanguage: 'Elige tu idioma',
    getStarted: 'Comenzar',
    swipeToContinue: 'Desliza hacia arriba o toca para continuar',
    chooseCategory: 'Elegir Categoría',
    selectType: 'Selecciona el tipo de nombres que buscas',
    male: 'Masculino',
    female: 'Femenino',
    unisex: 'Unisex',
    traditionalMasculine: 'Nombres masculinos tradicionales',
    beautifulFeminine: 'Hermosos nombres femeninos',
    modernNeutral: 'Nombres modernos neutros',
    tapCard: 'Toca una tarjeta para continuar tu viaje',
    chooseOrigin: 'Elegir Origen',
    selectCultural: 'Selecciona el origen cultural para tus nombres',
    names: 'nombres',
    chooseFeeling: 'Elegir Sentimiento',
    selectEmotional: 'Selecciona la esencia emocional para tus nombres',
    eachFeeling: 'Cada sentimiento crea un tono emocional único para tus nombres',
    generateNames: 'Generar Nombres',
    fineTune: 'Ajusta tus preferencias para resultados perfectos',
    yourSelection: 'Tu Selección',
    origin: 'Origen',
    gender: 'Género',
    culturalOrigin: 'Origen Cultural',
    numberOfNames: 'Número de nombres',
    chooseBetween: 'Elige entre 1 y 10 nombres para generar',
    generateBeautiful: 'Generar Nombres Hermosos',
    back: 'Atrás',
    next: 'Siguiente',
    startOver: 'Empezar de Nuevo',
    feeling: 'Sentimiento',
    // Origins in Spanish
    arabic: 'Árabe',
    islamic: 'Islámico',
    asian: 'Asiático',
    western: 'Occidental',
    latin: 'Latinoamericano',
    northAmerican: 'Norteamericano',
    european: 'Europeo',
    african: 'Africano',
    jewish: 'Judío',
    slavic: 'Eslavo',
    scandinavian: 'Escandinavo',
    oceanic: 'Oceánico',
    korean: 'Coreano',
    japanese: 'Japonés',
    global: 'Mezcla Global',
    // Feelings in Spanish
    strong: 'Fuerte',
    soft: 'Suave',
    brave: 'Valiente',
    mysterious: 'Misterioso',
    wise: 'Sabio',
    joyful: 'Alegre',
    noble: 'Noble',
    peaceful: 'Pacífico',
    passionate: 'Apasionado',
    unique: 'Único',
    creative: 'Creativo',
    adventurous: 'Aventurero',
    elegant: 'Elegante',
    loyal: 'Leal',
    radiant: 'Radiante',
    readyToDiscover: 'Listo para Descubrir Nombres',
    generateBeautiful: 'Generar hermosos',
    names: 'nombres',
    from: 'de',
    culturalTraditions: 'tradiciones culturales',
    meaningfulOrigins: 'Orígenes significativos',
    meaningfulOriginsDesc: 'Nombres con profundo significado cultural',
    culturalAuthenticity: 'Autenticidad cultural',
    culturalAuthenticityDesc: 'Nombres auténticos de tradiciones reales',
    easyToCopy: 'Fácil de copiar y compartir',
    easyToCopyDesc: 'Funcionalidad simple de copiar y compartir',
  },
  ru: {
    nameCraft: 'NameCraft', // Keep in English
    discoverNames: 'Откройте значимые имена из культур всего мира',
    chooseLanguage: 'Выберите язык',
    getStarted: 'Начать',
    swipeToContinue: 'Проведите вверх или нажмите, чтобы продолжить',
    chooseCategory: 'Выбрать Категорию',
    selectType: 'Выберите тип имен, которые вы ищете',
    male: 'Мужской',
    female: 'Женский',
    unisex: 'Унисекс',
    traditionalMasculine: 'Традиционные мужские имена',
    beautifulFeminine: 'Красивые женские имена',
    modernNeutral: 'Современные нейтральные имена',
    tapCard: 'Нажмите на карточку, чтобы продолжить путешествие',
    chooseOrigin: 'Выбрать Происхождение',
    selectCultural: 'Выберите культурное происхождение для ваших имен',
    names: 'имена',
    chooseFeeling: 'Выбрать Чувство',
    selectEmotional: 'Выберите эмоциональную сущность для ваших имен',
    eachFeeling: 'Каждое чувство создает уникальный эмоциональный тон для ваших имен',
    generateNames: 'Генерировать Имена',
    fineTune: 'Настройте ваши предпочтения для идеальных результатов',
    yourSelection: 'Ваш Выбор',
    origin: 'Происхождение',
    gender: 'Пол',
    culturalOrigin: 'Культурное Происхождение',
    numberOfNames: 'Количество имен',
    chooseBetween: 'Выберите от 1 до 10 имен для генерации',
    generateBeautiful: 'Генерировать Красивые Имена',
    back: 'Назад',
    next: 'Далее',
    startOver: 'Начать Заново',
    feeling: 'Чувство',
    // Origins in Russian
    arabic: 'Арабский',
    islamic: 'Исламский',
    asian: 'Азиатский',
    western: 'Западный',
    latin: 'Латиноамериканский',
    northAmerican: 'Североамериканский',
    european: 'Европейский',
    african: 'Африканский',
    jewish: 'Еврейский',
    slavic: 'Славянский',
    scandinavian: 'Скандинавский',
    oceanic: 'Океанический',
    korean: 'Корейский',
    japanese: 'Японский',
    global: 'Глобальная Смесь',
    // Feelings in Russian
    strong: 'Сильный',
    soft: 'Мягкий',
    brave: 'Храбрый',
    mysterious: 'Таинственный',
    wise: 'Мудрый',
    joyful: 'Радостный',
    noble: 'Благородный',
    peaceful: 'Мирный',
    passionate: 'Страстный',
    unique: 'Уникальный',
    creative: 'Творческий',
    adventurous: 'Авантюрный',
    elegant: 'Элегантный',
    loyal: 'Верный',
    radiant: 'Сияющий',
    readyToDiscover: 'Готов Открыть Имена',
    generateBeautiful: 'Генерировать красивые',
    names: 'имена',
    from: 'из',
    culturalTraditions: 'культурных традиций',
    meaningfulOrigins: 'Значимые истоки',
    meaningfulOriginsDesc: 'Имена с глубоким культурным значением',
    culturalAuthenticity: 'Культурная аутентичность',
    culturalAuthenticityDesc: 'Аутентичные имена из реальных традиций',
    easyToCopy: 'Легко копировать и делиться',
    easyToCopyDesc: 'Простая функция копирования и обмена',
  },
  de: {
    nameCraft: 'NameCraft', // Keep in English
    discoverNames: 'Entdecken Sie bedeutungsvolle Namen aus Kulturen der ganzen Welt',
    chooseLanguage: 'Wählen Sie Ihre Sprache',
    getStarted: 'Loslegen',
    swipeToContinue: 'Nach oben wischen oder tippen zum Fortfahren',
    chooseCategory: 'Kategorie Wählen',
    selectType: 'Wählen Sie den Typ der Namen, nach denen Sie suchen',
    male: 'Männlich',
    female: 'Weiblich',
    unisex: 'Unisex',
    traditionalMasculine: 'Traditionelle männliche Namen',
    beautifulFeminine: 'Schöne weibliche Namen',
    modernNeutral: 'Moderne geschlechtsneutrale Namen',
    tapCard: 'Tippen Sie auf eine Karte, um Ihre Reise fortzusetzen',
    chooseOrigin: 'Herkunft Wählen',
    selectCultural: 'Wählen Sie die kulturelle Herkunft für Ihre Namen',
    names: 'Namen',
    chooseFeeling: 'Gefühl Wählen',
    selectEmotional: 'Wählen Sie die emotionale Essenz für Ihre Namen',
    eachFeeling: 'Jedes Gefühl schafft einen einzigartigen emotionalen Ton für Ihre Namen',
    generateNames: 'Namen Generieren',
    fineTune: 'Verfeinern Sie Ihre Präferenzen für perfekte Ergebnisse',
    yourSelection: 'Ihre Auswahl',
    origin: 'Herkunft',
    gender: 'Geschlecht',
    culturalOrigin: 'Kulturelle Herkunft',
    numberOfNames: 'Anzahl der Namen',
    chooseBetween: 'Wählen Sie zwischen 1 und 10 Namen zur Generierung',
    generateBeautiful: 'Schöne Namen Generieren',
    back: 'Zurück',
    next: 'Weiter',
    startOver: 'Neu Beginnen',
    feeling: 'Gefühl',
    // Origins in German
    arabic: 'Arabisch',
    islamic: 'Islamisch',
    asian: 'Asiatisch',
    western: 'Westlich',
    latin: 'Lateinamerikanisch',
    northAmerican: 'Nordamerikanisch',
    european: 'Europäisch',
    african: 'Afrikanisch',
    jewish: 'Jüdisch',
    slavic: 'Slawisch',
    scandinavian: 'Skandinavisch',
    oceanic: 'Ozeanisch',
    korean: 'Koreanisch',
    japanese: 'Japanisch',
    global: 'Globale Mischung',
    // Feelings in German
    strong: 'Stark',
    soft: 'Sanft',
    brave: 'Mutig',
    mysterious: 'Geheimnisvoll',
    wise: 'Weise',
    joyful: 'Freudig',
    noble: 'Edel',
    peaceful: 'Friedlich',
    passionate: 'Leidenschaftlich',
    unique: 'Einzigartig',
    creative: 'Kreativ',
    adventurous: 'Abenteuerlich',
    elegant: 'Elegant',
    loyal: 'Loyal',
    radiant: 'Strahlend',
    readyToDiscover: 'Bereit Namen zu Entdecken',
    generateBeautiful: 'Schöne generieren',
    names: 'Namen',
    from: 'aus',
    culturalTraditions: 'kulturellen Traditionen',
    meaningfulOrigins: 'Bedeutungsvolle Ursprünge',
    meaningfulOriginsDesc: 'Namen mit tiefer kultureller Bedeutung',
    culturalAuthenticity: 'Kulturelle Authentizität',
    culturalAuthenticityDesc: 'Authentische Namen aus echten Traditionen',
    easyToCopy: 'Einfach zu kopieren und teilen',
    easyToCopyDesc: 'Einfache Kopier- und Teilen-Funktionalität',
  },
  ja: {
    nameCraft: 'NameCraft', // Keep in English
    discoverNames: '世界中の文化から意味のある名前を発見する',
    chooseLanguage: '言語を選択',
    getStarted: '始める',
    swipeToContinue: '上にスワイプまたはタップして続行',
    chooseCategory: 'カテゴリを選択',
    selectType: '探している名前のタイプを選択してください',
    male: '男性',
    female: '女性',
    unisex: 'ユニセックス',
    traditionalMasculine: '伝統的な男性名',
    beautifulFeminine: '美しい女性名',
    modernNeutral: '現代的な中性名',
    tapCard: 'カードをタップして旅を続ける',
    chooseOrigin: '起源を選択',
    selectCultural: 'あなたの名前の文化的起源を選択してください',
    names: '名前',
    chooseFeeling: '感情を選択',
    selectEmotional: 'あなたの名前の感情的な本質を選択してください',
    eachFeeling: '各感情はあなたの名前に独特な感情的なトーンを作ります',
    generateNames: '名前を生成',
    fineTune: '完璧な結果のために好みを微調整',
    yourSelection: 'あなたの選択',
    origin: '起源',
    gender: '性別',
    culturalOrigin: '文化的起源',
    numberOfNames: '名前の数',
    chooseBetween: '生成する名前を1から10の間で選択',
    generateBeautiful: '美しい名前を生成',
    back: '戻る',
    next: '次へ',
    startOver: '最初から始める',
    feeling: '感情',
    // Origins in Japanese
    arabic: 'アラビア',
    islamic: 'イスラム',
    asian: 'アジア',
    western: '西洋',
    latin: 'ラテンアメリカ',
    northAmerican: '北米',
    european: 'ヨーロッパ',
    african: 'アフリカ',
    jewish: 'ユダヤ',
    slavic: 'スラブ',
    scandinavian: 'スカンジナビア',
    oceanic: 'オセアニア',
    korean: '韓国',
    japanese: '日本',
    global: 'グローバルミックス',
    // Feelings in Japanese
    strong: '強い',
    soft: '優しい',
    brave: '勇敢',
    mysterious: '神秘的',
    wise: '賢い',
    joyful: '喜びに満ちた',
    noble: '高貴',
    peaceful: '平和',
    passionate: '情熱的',
    unique: 'ユニーク',
    creative: '創造的',
    adventurous: '冒険的',
    elegant: 'エレガント',
    loyal: '忠実',
    radiant: '輝く',
    readyToDiscover: '名前を発見する準備完了',
    generateBeautiful: '美しい',
    names: '名前',
    from: 'から',
    culturalTraditions: '文化的伝統',
    meaningfulOrigins: '意味のある起源',
    meaningfulOriginsDesc: '深い文化的意味を持つ名前',
    culturalAuthenticity: '文化的真実性',
    culturalAuthenticityDesc: '真の伝統からの本物の名前',
    easyToCopy: 'コピーと共有が簡単',
    easyToCopyDesc: 'シンプルなコピーと共有機能',
  },
  zh: {
    nameCraft: 'NameCraft', // Keep in English
    discoverNames: '发现来自世界各地文化的有意义名字',
    chooseLanguage: '选择您的语言',
    getStarted: '开始',
    swipeToContinue: '向上滑动或点击继续',
    chooseCategory: '选择类别',
    selectType: '选择您要寻找的名字类型',
    male: '男性',
    female: '女性',
    unisex: '中性',
    traditionalMasculine: '传统男性名字',
    beautifulFeminine: '美丽女性名字',
    modernNeutral: '现代中性名字',
    tapCard: '点击卡片继续您的旅程',
    chooseOrigin: '选择起源',
    selectCultural: '为您的名字选择文化起源',
    names: '名字',
    chooseFeeling: '选择感觉',
    selectEmotional: '为您的名字选择情感本质',
    eachFeeling: '每种感觉为您的名字创造独特的情感色调',
    generateNames: '生成名字',
    fineTune: '微调您的偏好以获得完美结果',
    yourSelection: '您的选择',
    origin: '起源',
    gender: '性别',
    culturalOrigin: '文化起源',
    numberOfNames: '名字数量',
    chooseBetween: '选择生成1到10个名字',
    generateBeautiful: '生成美丽名字',
    back: '返回',
    next: '下一步',
    startOver: '重新开始',
    feeling: '感觉',
    // Origins in Chinese
    arabic: '阿拉伯',
    islamic: '伊斯兰',
    asian: '亚洲',
    western: '西方',
    latin: '拉丁美洲',
    northAmerican: '北美',
    european: '欧洲',
    african: '非洲',
    jewish: '犹太',
    slavic: '斯拉夫',
    scandinavian: '斯堪的纳维亚',
    oceanic: '大洋洲',
    korean: '韩国',
    japanese: '日本',
    global: '全球混合',
    // Feelings in Chinese
    strong: '强壮',
    soft: '温柔',
    brave: '勇敢',
    mysterious: '神秘',
    wise: '智慧',
    joyful: '快乐',
    noble: '高贵',
    peaceful: '和平',
    passionate: '热情',
    unique: '独特',
    creative: '创意',
    adventurous: '冒险',
    elegant: '优雅',
    loyal: '忠诚',
    radiant: '光芒四射',
    readyToDiscover: '准备发现名字',
    generateBeautiful: '生成美丽的',
    names: '名字',
    from: '来自',
    culturalTraditions: '文化传统',
    meaningfulOrigins: '有意义的起源',
    meaningfulOriginsDesc: '具有深刻文化意义的名字',
    culturalAuthenticity: '文化真实性',
    culturalAuthenticityDesc: '来自真实传统的真实名字',
    easyToCopy: '易于复制和分享',
    easyToCopyDesc: '简单的复制和分享功能',
  },
  hi: {
    nameCraft: 'NameCraft', // Keep in English
    discoverNames: 'दुनिया भर की संस्कृतियों से सार्थक नामों की खोज करें',
    chooseLanguage: 'अपनी भाषा चुनें',
    getStarted: 'शुरू करें',
    swipeToContinue: 'जारी रखने के लिए ऊपर स्वाइप करें या टैप करें',
    chooseCategory: 'श्रेणी चुनें',
    selectType: 'आप जिस प्रकार के नाम खोज रहे हैं उसे चुनें',
    male: 'पुरुष',
    female: 'महिला',
    unisex: 'यूनिसेक्स',
    traditionalMasculine: 'पारंपरिक पुरुष नाम',
    beautifulFeminine: 'सुंदर महिला नाम',
    modernNeutral: 'आधुनिक तटस्थ नाम',
    tapCard: 'अपनी यात्रा जारी रखने के लिए एक कार्ड पर टैप करें',
    chooseOrigin: 'मूल चुनें',
    selectCultural: 'अपने नामों के लिए सांस्कृतिक मूल चुनें',
    names: 'नाम',
    chooseFeeling: 'भावना चुनें',
    selectEmotional: 'अपने नामों के लिए भावनात्मक सार चुनें',
    eachFeeling: 'हर भावना आपके नामों के लिए एक अनोखा भावनात्मक स्वर बनाती है',
    generateNames: 'नाम जेनरेट करें',
    fineTune: 'सही परिणामों के लिए अपनी प्राथमिकताओं को बेहतर बनाएं',
    yourSelection: 'आपका चयन',
    origin: 'मूल',
    gender: 'लिंग',
    culturalOrigin: 'सांस्कृतिक मूल',
    numberOfNames: 'नामों की संख्या',
    chooseBetween: 'जेनरेट करने के लिए 1 से 10 नामों के बीच चुनें',
    generateBeautiful: 'सुंदर नाम जेनरेट करें',
    back: 'वापस',
    next: 'अगला',
    startOver: 'फिर से शुरू करें',
    feeling: 'भावना',
    // Origins in Hindi
    arabic: 'अरबी',
    islamic: 'इस्लामी',
    asian: 'एशियाई',
    western: 'पश्चिमी',
    latin: 'लैटिन अमेरिकी',
    northAmerican: 'उत्तर अमेरिकी',
    european: 'यूरोपीय',
    african: 'अफ्रीकी',
    jewish: 'यहूदी',
    slavic: 'स्लाविक',
    scandinavian: 'स्कैंडिनेवियाई',
    oceanic: 'ओशिनिक',
    korean: 'कोरियाई',
    japanese: 'जापानी',
    global: 'ग्लोबल मिक्स',
    // Feelings in Hindi
    strong: 'मजबूत',
    soft: 'कोमल',
    brave: 'बहादुर',
    mysterious: 'रहस्यमय',
    wise: 'बुद्धिमान',
    joyful: 'खुशमिजाज',
    noble: 'कुलीन',
    peaceful: 'शांतिप्रिय',
    passionate: 'भावुक',
    unique: 'अनोखा',
    creative: 'रचनात्मक',
    adventurous: 'साहसिक',
    elegant: 'सुरुचिपूर्ण',
    loyal: 'वफादार',
    radiant: 'तेजस्वी',
    readyToDiscover: 'नाम खोजने के लिए तैयार',
    generateBeautiful: 'सुंदर उत्पन्न करें',
    names: 'नाम',
    from: 'से',
    culturalTraditions: 'सांस्कृतिक परंपराएं',
    meaningfulOrigins: 'सार्थक मूल',
    meaningfulOriginsDesc: 'गहरे सांस्कृतिक महत्व वाले नाम',
    culturalAuthenticity: 'सांस्कृतिक प्रामाणिकता',
    culturalAuthenticityDesc: 'वास्तविक परंपराओं से प्रामाणिक नाम',
    easyToCopy: 'कॉपी और शेयर करने में आसान',
    easyToCopyDesc: 'सरल कॉपी और शेयर कार्यक्षमता',
  }
};

const useNameStore = create(
  persist(
    (set, get) => ({
      // Theme state - Default to dark for premium feel
      isDarkMode: true,
      toggleDarkMode: () => set((state) => ({ isDarkMode: !state.isDarkMode })),

      // Wizard flow state
      currentStep: 'landing', // 'landing', 'gender', 'region', 'feeling', 'generator'
      selectedLanguage: 'en',
      selectedGender: null, // 'male', 'female', 'unisex'
      selectedRegion: null, // 'arabic', 'islamic', 'asian', 'western', etc.
      selectedFeeling: null, // 'strong', 'soft', 'brave', 'mysterious', etc.
      
      // Translation helper
      t: (key) => {
        const state = get();
        return translations[state.selectedLanguage]?.[key] || translations.en[key] || key;
      },
      
      // Navigation
      setStep: (step) => set({ currentStep: step }),
      setLanguage: (language) => set({ selectedLanguage: language }),
      setGender: (gender) => set({ selectedGender: gender }),
      setRegion: (region) => set({ selectedRegion: region }),
      setFeeling: (feeling) => set({ selectedFeeling: feeling }),

      // Filter state (legacy - keeping for compatibility)
      filters: {
        gender: '',
        culture: '',
        count: 5, // Default to 5 names, max 10
      },
      setFilters: (newFilters) =>
        set((state) => ({
          filters: { ...state.filters, ...newFilters },
        })),

      // Generated names
      generatedNames: [],
      setGeneratedNames: (names) => set({ generatedNames: names }),

      // UI state
      isGenerating: false,
      setIsGenerating: (loading) => set({ isGenerating: loading }),

      // Animation state
      isTransitioning: false,
      setIsTransitioning: (transitioning) => set({ isTransitioning: transitioning }),

      // Last generation timestamp
      lastGenerated: null,
      setLastGenerated: () => set({ lastGenerated: Date.now() }),

      // Navigation methods
      goToGenderSelection: () => {
        set({ isTransitioning: true });
        setTimeout(() => {
          set({ currentStep: 'gender', isTransitioning: false });
        }, 200); // Reduced delay for smoother transitions
      },

      goToRegionSelection: (gender) => {
        set({ selectedGender: gender, isTransitioning: true });
        setTimeout(() => {
          set({ currentStep: 'region', isTransitioning: false });
        }, 400); // Reduced delay
      },

      goToFeelingSelection: (region) => {
        set({ selectedRegion: region, isTransitioning: true });
        setTimeout(() => {
          set({ currentStep: 'feeling', isTransitioning: false });
        }, 400); // New feeling selection step
      },

      goToGenerator: (feeling) => {
        set({ selectedFeeling: feeling, isTransitioning: true });
        setTimeout(() => {
          set({ currentStep: 'generator', isTransitioning: false });
        }, 400);
      },

      // Go back methods
      goBack: () => {
        const currentStep = get().currentStep;
        set({ isTransitioning: true });
        setTimeout(() => {
          switch (currentStep) {
            case 'gender':
              set({ currentStep: 'landing', isTransitioning: false });
              break;
            case 'region':
              set({ currentStep: 'gender', isTransitioning: false });
              break;
            case 'feeling':
              set({ currentStep: 'region', isTransitioning: false });
              break;
            case 'generator':
              set({ currentStep: 'feeling', isTransitioning: false });
              break;
            default:
              set({ isTransitioning: false });
          }
        }, 300);
      },

      // Reset wizard
      resetWizard: () => set({
        currentStep: 'landing',
        selectedLanguage: 'en',
        selectedGender: null,
        selectedRegion: null,
        selectedFeeling: null,
        generatedNames: [],
        lastGenerated: null,
        isTransitioning: false,
      }),

      // Clear all data
      clearData: () =>
        set({
          generatedNames: [],
          lastGenerated: null,
          filters: { gender: '', culture: '', count: 5 },
        }),
    }),
    {
      name: 'name-generator-storage',
      partialize: (state) => ({ 
        isDarkMode: state.isDarkMode, 
        selectedLanguage: state.selectedLanguage,
        filters: state.filters 
      }),
    }
  )
);

export default useNameStore; 